logging:
  level:
    com.example.demo: "INFO"
    org.springframework: "INFO"

spring:
  application:
    name: "@project.JavaSQL@"
  banner:
    location: classpath:banner.txt
  datasource:
    url: jdbc:mysql://localhost:3306/people
    username: root
    password: pwd123
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    locations: db/migration
  jpa:
    open-in-view: false


