logging:
  level:
    com.example.demo: "INFO"
    org.springframework: "INFO"
    org.springframework.cache: "DEBUG"

spring:
  application:
    name: "@project.JavaSQL@"
  banner:
    location: classpath:banner.txt
  datasource:
    url: jdbc:mysql://localhost:3306/people
    username: root
    password: pwd123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
  redis:
    host: localhost
    port: 6379
    clientType: jedis
    use-key-prefix: true
    key-prefix: javasql-
  cache:
    type: redis
    redis:
      time-to-live: 300000
      cache-null-values: false
  flyway:
    locations: db/migration
